#!/usr/bin/env bash

# https://grpc-go-sandbox-xxxxxx-an.a.run.app
ENDPOINT=$1

grpcurl \
  -proto protos/calculator.proto \
  -d '{"first_operand": 3.0, "second_operand": 3.0, "operation": "ADD"}' \
  ${ENDPOINT#https://}:443 \
  Calculator.Calculate
